- name: install  centos 7 postgres yum repo
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7.2-x86_64/pgdg-centos94-9.4-2.noarch.rpm state=present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'



- name: install  centos 6 postgres yum repo
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-2.noarch.rpm state=present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: Install Standalone Postgresql Server
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - postgresql94-server-9.4.6
    - postgresql94-contrib-9.4.6
    - postgresql94-devel-9.4.6
    - python-psycopg2

#- command: service postgresql initdb
#- command: chkconfig postgresql on

#- service: name=postgresql state=started
