---

- name: Install NTP
  yum: name={{ item }} state=installed
  with_items: 
    - ntp

- name: NTP Configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    restart ntpd

- service: name=ntpd state=started enabled=yes
