- name: Check kvm compatible
  command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: cpu

- name: Apt install cpu-checker
  apt: name=cpu-checker state=installed

- command: kvm-ok
  register: kvmok

- fail: msg="kvm can no installed on {{ ansible_hostname }}"
  when: cpu.stdout|int < 1 or kvmok.stdout.find("KVM acceleration can be used")

- name: Install kvm requried packages
  apt: name="{{ item }}" state=installed
  with_items:
    - qemu-kvm 
    - libvirt-bin 
    - ubuntu-vm-builder 
    - bridge-utils
    - qemu
    - virt-manager
