- name: Check kvm compatible
  command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: cpu

- name: Apt install cpu-checker
  apt: name=cpu-checker state=installed

- command: kvm-ok
  register: kvmok

- debug: msg="{{ kvmok.stdout.find('KVM acceleration can be used') }}"
- fail: msg="kvm can not install on {{ ansible_hostname }}"
  when: cpu.stdout|int < 1 or kvmok.stdout.find("KVM acceleration can be used") == -1

- name: Install kvm requried packages
  apt: name="{{ item }}" state=installed
  with_items:
    - qemu-kvm 
    - libvirt-bin 
    - ubuntu-vm-builder 
    - bridge-utils
    - qemu
    - virt-manager

- name: Ensure libvirt-bin started
  service: name=libvirt-bin state=started
