ipaclient_base_command: ipa-client-install -U 
ipaserver_configure_ssh: True
ipaserver_configure_sshd: True
ipaserver_dns_forwarder: 8.8.8.8
ipaserver_domain: "{{ ansible_domain }}"
ipaserver_hbac_allow: True
ipaserver_idstart: 5000
ipaserver_idmax: False
ipaserver_mkhomedir: True
ipaclient_packages:
  - ipa-client
  - oddjob-mkhomedir
ipaserver_realm: "{{ ansible_domain|upper }}"
ipaserver_setup_dns: True
ipaserver_setup_ntp: True
ipaserver_ssh_trust_dns: True
ipaserver_ui_redirect: True
ipaserver_manage_firewalld: True
ipaserver_server: "{{  hostvars[groups['freeipa-master'][0]]['ansible_fqdn'] }}"
ipaserver_admin_password: password
ipaserver_admin: admin
ipaclient_nameserver: "{{  hostvars[groups['freeipa-master'][0]]['ansible_eth0']['ipv4']['address'] }}"
