---
- name: get kibana zip
  get_url: url=https://download.elastic.co/kibana/kibana/kibana-4.3.1-linux-x64.tar.gz dest=/root

- name: Download d64e1fc0ddeaaab85e168177de6c78ed82bb3a3b  kibana-4.3.0-linux-x64.tar.gz
  unarchive: src=/root/kibana-4.3.1-linux-x64.tar.gz dest=/usr/share/ copy=no

- name: creat soft link
  file: src=/usr/share/kibana-4.3.1-linux-x64 dest=/usr/share/kibana state=link

- name: copy config
  template: src=kibana.yml dest=/usr/share/kibana/config/kibana.yml

- name: copy kibana init.d
  copy: src=kibana4_init dest=/etc/init.d/kibana mode=755

- name: start kibana
  service: name=kibana state=started
