---
- name: installl zabbix-repo
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm  state=present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: installl zabbix-server,web,postgresql,sender
  yum: name={{ item }}  state=latest
  with_items:
    - zabbix-server-pgsql
    - zabbix-web-pgsql
    - zabbix-sender
    - zabbix-web
    - postgresql-server
    - python-psycopg2

- selinux: state=disabled

- firewalld: port={{ item }} permanent=true state=enabled immediate=yes
  with_items:
    - 10050/tcp
    - 10051/tcp
    - 80/tcp
    - 443/tcp
    - 5432/tcp

- name: copy zabbix-server.conf
  template: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf

- stat: path=/var/lib/pgsql/data/base
  register: data_dir

- file: path=/var/lib/pgsql owner=postgres group=postgres mode=755 state=directory 
  when: data_dir.stat.exists != True 

- shell: postgresql-setup initdb
  when: data_dir.stat.exists != True

- name: listen on all ip
  lineinfile: dest=/var/lib/pgsql/data/postgresql.conf  regexp='^(.*)listen_addresses(.*)$' line="listen_addresses = '*'"

- name: pg_hba.conf
  lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf   line="host    all             all             10.0.0.0/8              md5"

- service: name=postgresql state=restarted enabled=yes

- name: create zabbix db in postgres
  become: yes
  become_user: postgres
  postgresql_db: name=zabbix encoding='UTF-8'

- name: create zabbix user
  become: yes
  become_user: postgres
  postgresql_user: db=zabbix name=zabbix password={{ DBPassword }}  priv=ALL state=present


- name: grant all to postgres user
  become: yes
  become_user: postgres
  postgresql_user: db=zabbix name=postgres,zabbix priv=ALL 

- shell: cd  /usr/share/doc/zabbix-server-pgsql-3.0.1/   && zcat create.sql.gz | psql  zabbix
  become: yes
  become_user: postgres
  ignore_errors: yes

- name: grant table priv to zabbix
  become: yes
  become_user: postgres
  postgresql_privs: >
    db=zabbix
    objs=ALL_IN_SCHEMA
    privs=ALL
    type=table
    role=zabbix
    grant_option=yes
    state=present

- name: replace data.timezone
  lineinfile: dest=/etc/httpd/conf.d/zabbix.conf regexp='^(.*)date.timezone(.*)$' line='        php_value date.timezone Pacific/Auckland'

- name: start httpd
  service: name=httpd state=restarted  enabled=yes

- name: start zabbix-server
  service: name=zabbix-server state=started enabled=yes


