---

- name: Create Jenkins SSL configuration folder.
  file: path=/etc/nginx/ssl state=directory
  when: jenkins_ssl_enabled

- name: Check SSL certificate 
  stat: path=/etc/nginx/ssl/jenkins.crt  
  register: cert

- name: Check SSL key
  stat: path=/etc/nginx/ssl/jenkins.key
  register: key

- name: Create self-signed certificate.
  command: >
    openssl req -new -nodes -x509 -subj "{{ jenkins_self_signed_cert_subj }}" -days 3650 -keyout {{ jenkins_ssl_certificate_key }} -out {{ jenkins_ssl_certificate }} -extensions v3_ca
    creates={{ jenkins_ssl_certificate }}
  when: jenkins_ssl_enabled and (cert.stat.exists == False or key.stat.exists == False)

- name: Configure Jenkins behind Nginx none SSL
  template: src=jenkins.conf.j2 dest=/etc/nginx/conf.d/jenkins.conf
  when: jenkins_ssl_enabled == False
  notify:
    restart nginx

- name: Configure Jenkins behind Nginx with SSL
  template: src=jenkins-ssl.conf.j2 dest=/etc/nginx/conf.d/jenkins.conf
  when: jenkins_ssl_enabled 
  notify:
    restart nginx

- name: Install required pkgs 
  yum: name="{{ item }}" state=installed
  with_items:
    - curl

- name: Install Jenkins repo
  shell: curl http://pkg.jenkins-ci.org/redhat/jenkins.repo > /etc/yum.repos.d/jenkins.repo 
  register: jenkins_repo
  
- command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
  when: jenkins_repo|changed

- name: Install Jenkins Server
  yum: name=jenkins state=installed 

- name: Ensure httpd_can_network_connect is true
  command: setsebool -P httpd_can_network_connect 1

- name: Configure Jenkins
  template: src=jenkins.j2 dest=/etc/sysconfig/jenkins mode=0600 owner=jenkins group=jenkins 

- name: Jenkins tmp
  file: path=/var/lib/jenkins/tmp state=directory owner=jenkins group=jenkins

- command: mount -o remount /tmp

- name: Ensure Jenkins service started
  service: name=jenkins state=started enabled=yes

# port 8080 should be disabled once SSL is enabled
- firewalld: port={{ item }} permanent=true zone=public state=enabled
  with_items:
    - 443/tcp
    - 80/tcp
  notify:
    - reload firewalld

