---

- file: path={{ GUACAMOLE_HOME }}  state=directory mode=0755 

- name: Configure Guacamole 
  template: src=guacamole.properties.j2 dest={{ GUACAMOLE_HOME }}/guacamole.properties mode=644
  notify:
    - restart guacd

- template: src=logback.xml.j2 dest={{ GUACAMOLE_HOME }}/logback.xml mode=644
  notify:
    - restart guacd

- template: src=user-mapping.xml.j2 dest={{ GUACAMOLE_HOME }}/user-mapping.xml mode=644
  notify:
    - restart guacd

#- template: src=guacConfigGroup.ldif.j2 dest="{{ GUACAMOLE_HOME }}/guacConfigGroup.ldif"
#  register: schema_ldif

#- name: adding new entry "cn=guacConfigGroup,cn=schema,cn=config"
#  command: ldapadd -Q -Y EXTERNAL -H ldapi:/// -f "{{ GUACAMOLE_HOME }}/guacConfigGroup.ldif"
#  when: schema_ldif.changed
  
#- template: src=userConfigGroup.ldif.j2 dest="{{ GUACAMOLE_HOME }}/userConfigGroup.ldif"
#  register: user_ldif

#- name: adding new entry "cn=admin,cn=example,cn=net"
#  command: ldapadd -x -D cn=admin,dc=example,dc=net -W -f "{{ GUACAMOLE_HOME }}/userConfigGroup.ldif"
#  when: user_ldif.changed
