---

- name: Install Tomcat 
  yum: name={{ item }} state=installed
  with_items: 
    - tomcat
    - tomcat-webapps
    - tomcat-admin-webapps

# port 8080 should be disabled once SSL is enabled
- firewalld: port={{ item }} permanent=true zone=public state=enabled
  with_items:
    - 8443/tcp
    - 8080/tcp
  notify:
    - reload firewalld

- name: Configure Tomcat
  template: src="{{ item }}.j2" dest="/etc/tomcat/{{ item }}"
  with_items:
    - tomcat-users.xml
    - server.xml
  notify:
    - restart tomcat

-  file: path=/etc/ssl/tomcat state=directory recurse=true owner=tomcat group=tomcat mode=755

- name: Configure SSL on Tomcat
  copy: src="{{ item }}" dest=/etc/ssl/tomcat owner=tomcat group=tomcat mode=0600
  with_items:
    - keystore

- service: name=tomcat state=started enabled=yes
