---

- name: restart atomic-openshift-master
  service: name=atomic-openshift-master state=restarted

- name: restart atomic-openshift-master-api
  service: name=atomic-openshift-master-api state=restarted

- name: restart atomic-openshift-node
  service: name=atomic-openshift-node state=restarted

- name: restart docker
  service: name=docker state=restarted
