---
- name: Hard set the hostname
  hostname: name={{ ansible_fqdn }}

- name: Add host entry for replica
  lineinfile:
    dest=/etc/hosts
    regexp=" {{ ansible_hostname }} "
    line="{{ ansible_eth0.ipv4.address }} {{ ansible_fqdn }}"
    owner=root
    group=root
    mode=0644
    state=present

- name: Ensure software is installed (yum)
  yum: name={{ item }} state=present
  with_items: ipaserver_packages
  when: ansible_distribution == "CentOS" or
        (ansible_distribution == "Fedora" and ansible_distribution_version|int <= 21)

- name: Ensure software is installed (dnf)
  dnf: name={{ item }} state=present
  with_items: ipaserver_packages
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int > 21

- name: Enable making home dir
  action: command
    authconfig
    --enablemkhomedir
    --update
  when: ipaserver_mkhomedir

- name: Fetch gpg file for replica
  copy: dest="/var/lib/ipa/replica-info-{{ ansible_fqdn }}.gpg" src="/tmp/replica-info-{{ ansible_fqdn }}.gpg" 

- include: firewalld.yml
  when: ipaserver_manage_firewalld

- name: Install the replica
  action: command
    {{ ipaserver_replica_install_command }}
    --setup-ca
    --admin-password {{ ipaserver_admin_password }}
    --ip-address={{ ansible_eth0.ipv4.address }}
    --password {{ ipaserver_dir_admin_password }}
    {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
    {{ '--forwarder=%s' % ipaserver_dns_forwarder
       if ipaserver_dns_forwarder | default(False) else '--no-forwarders' }}
    {{ '--setup-dns' if ipaserver_setup_dns | default(True) else '' }}
    {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }}
    --skip-conncheck
    --debug
    /var/lib/ipa/replica-info-{{ ansible_fqdn }}.gpg
  async: 1200
  poll: 15
  tags: sync

